name: Install Bun from CNPM
description: For faster installation of Bun in China.
branding:
  icon: play-circle
  color: red

inputs: {}
outputs: {}

runs:
  using: composite
  steps:
    - shell: bash
      if: runner.os == 'Windows'
      run: |
        echo "::error title=Unsupported OS::Windows is not supported yet."
        exit 1
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        chmod +x ./install.sh
        ./install.sh
        echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
        echo "$HOME/.bun/bin" >> $GITHUB_PATH
