name: 测试

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: bun -v
